### ISSUE TITLE
Client Keybinds Bypass Server Permissions

### ISSUE THREAD

**Issue by onycius** [YukkuriLaboratory/FabPose#13]
Fabric 1.21
fabpose-1.0.2+1.21.jar
LuckPerms-Fabric-5.4.139

It seems that the server permissions only apply to the pose commands, not the actual action of performing a pose. This allows players without the necessary permissions to bypass restrictions and pose using keybinds if they have the mod installed on their client.

**Comment by turtton** [comment]
Sorry for late. Fixed in `1.0.3+1.21`
