### ISSUE TITLE
Client disconnected with reason: Received a registry entry that is unknown to this client

### ISSUE THREAD

**Issue by tinmarr** [YukkuriLaboratory/FabPose#6]
I get this error when i try to connect to the server:

![image](https://github.com/YukkuriLaboratory/FabPose/assets/35586618/40e7b16e-fc73-4219-9ba9-a2ca157974f5)

Mod is installed only on the server.

**Comment by turtton** [comment]
My apologies for the late reply. This issue has been fixed in 1.0.1+1.20.4.
Thank you for reporting!!
